# 开发环境配置
server:
  port: 3000

# 日志配置
logging:
  level:
    root: DEBUG
    com.miniprogram: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 微信小程序配置
wechat:
  miniprogram:
    app-id: wx9b30f4663bae806e
    app-secret: 7361ddd1b132692745c5549d90ee1a82


